[#3] 프로필 설정 페이지
f-lab-edu/grape-repo pull request #23
Opened 2024-08-18 05:56 UTC by xxziiko

## 변경사항

- [x] 프로필 설정 기능
  - 프로필 설정 페이지를 따로 만들지 않고, 
  기존 회원가입&로그인 페이지에 프로필 설정 컴포넌트 조건부 렌더링하는 형태로 변경했습니다.
  - 현재는 이름만 설정 가능하고, 추후에 프로필 이미지 선택 기능을 추가할 예정입니다. 
- 피드백 주셨던 애러 객체를 이중으로 감쌌던 부분도 수정했습니다!

2024-08-18 06:59 UTC, f-lab-jake requested changes

2024-08-18 06:59 UTC, f-lab-jake commented on src/entities/auth/api/signInUser.tsx
> +  if (error) throw error.message;
이러면 정보를 잃어버립니다. 에러를 받아서 처리하는쪽에서 메시지만 받아야할 이유가있나요?

2024-08-18 06:59 UTC, f-lab-jake commented on src/features/loginForm/model/useLoginMutation.tsx
> +  const { hasUserNameHandler } = useAuth();
`xHandler`같은 명명은 `x`가 이벤트일때 말이됩니다.

2024-08-18 06:59 UTC, f-lab-jake commented on src/features/loginForm/model/useSignUpMutation.tsx
> +      const hasUserName = await checkUserNameExists(data?.user.email as string);
`as` 안쓸수있게 못고치나요? 그리고 ?가 있는데 틀린 `as`같은데요?

2024-08-18 06:59 UTC, f-lab-jake commented on src/features/profileForm/ui/ProfileForm.tsx
> +  const [userName, setUserName] = useState<string>('');
react-hook-form 같은걸 쓰세요. 폼 로직은 금방 복잡해집니다.

2024-08-18 07:22 UTC, xxziiko commented on src/entities/auth/api/signInUser.tsx
> +  if (error) throw error.message;
아! 무슨 의미인지 이해했습니다

2024-08-19 09:00 UTC, xxziiko commented
@f-lab-jake 멘토님 피드백 반영했습니다!

2024-08-20 08:05 UTC, f-lab-jake requested changes

2024-08-20 08:05 UTC, f-lab-jake commented on src/entities/auth/api/signInUser.tsx
>  };
이 보일러플레이트를 함수를 써서 해결해보세요

2024-08-20 08:05 UTC, f-lab-jake commented on src/entities/auth/model/AuthProvider.tsx
> +    <AuthContext.Provider value={{ user, hasUserName, updateUserNameStatus }}>
상태 설계를 개선해보세요. 그냥 `updateUserNameStatus(true)`를 호출하면 유저명이 있느걸로 간주된다느건데 위험하지 않나요?

2024-08-20 15:08 UTC, xxziiko commented on src/entities/auth/api/signInUser.tsx
>  };
[1cc1c0b](https://github.com/f-lab-edu/grape-repo/pull/23/commits/1cc1c0ba370f344bad45d3a8818cd0bfacfc9c56) 이걸 의도한게 맞으실까요?

2024-08-20 15:10 UTC, xxziiko commented on src/entities/auth/model/AuthProvider.tsx
> +    <AuthContext.Provider value={{ user, hasUserName, updateUserNameStatus }}>
@f-lab-jake  [7df8605](https://github.com/f-lab-edu/grape-repo/pull/23/commits/7df86054633e179d8709809cc161db5cae12e4a1) 앗, 동의합니다. 다시 개선했습니다!

2024-08-22 01:35 UTC, f-lab-jake commented on src/entities/auth/model/AuthProvider.tsx
> +    <AuthContext.Provider value={{ user, hasUserName, updateUserNameStatus }}>
아뇨 제 의도는 그냥 username 자체를 atom에 저장하라는겁니다.

2024-08-22 14:34 UTC, xxziiko commented on src/entities/auth/model/AuthProvider.tsx
> +    <AuthContext.Provider value={{ user, hasUserName, updateUserNameStatus }}>
@f-lab-jake 아아 이해했습니다! 다시 개선했습니다 [889cf76](https://github.com/f-lab-edu/grape-repo/pull/23/commits/889cf7695b6189a2c346a76316e6e7090eaad1b9)

2024-08-24 13:36 UTC, f-lab-jake requested changes

2024-08-24 13:36 UTC, f-lab-jake commented on src/entities/auth/model/AuthProvider.tsx
> +  const handleUserName = (username: string) => {
요런건 그냥 `hanelUserName = setUserName`하면 됩니다.
그리고 사실 이렇게 할 필요도 없습니다.

이 함수를 쓰는 입장에서 이름이 `setUserName`이 낫습니다.

2024-08-24 13:36 UTC, f-lab-jake commented on src/features/loginForm/model/useLoginMutation.tsx
> +      handleSession(data.session);
여기서 함수이름이 `handleSession`이면 뭘하겠다는건지 어떻게 알수있을까요?
`handleSession`은 뭔지모르겠지만 그냥 `session`값을 달라, 라는 아무 의미업는 함수명입니다. 실제로 뭘하는지를 이름으로 쓰세요.

2024-08-24 14:12 UTC, xxziiko commented
@f-lab-jake 다시 개선했습니다!

2024-08-25 03:31 UTC, f-lab-jake approved these changes

2024-08-25 09:08 UTC, merged