[#26] 1:1 채팅 기능
f-lab-edu/grape-repo pull request #27
Opened 2024-08-31 08:20 UTC by xxziiko

## 변경 사항

- [x] 친구목록 fetch
- [x] 채팅목록 fetch (realtime 미적용)
- [x] 채팅방 1:1 대화 기능
  - supabse realtime 적용

2024-09-01 11:25 UTC, f-lab-jake requested changes

2024-09-01 11:25 UTC, f-lab-jake commented on src/apps/routes/_pub.tsx
>    },
줄여보세요.

2024-09-01 11:25 UTC, f-lab-jake commented on src/entities/auth/model/AuthProvider.tsx
> +  }, [location]);
좀 의심스러운 형태인데, 어떤 의도인가요?

2024-09-01 11:25 UTC, f-lab-jake commented on src/features/chat/apis/fetchMessagesForChat.tsx
> +  return data;
더 잘할수있습니다.

2024-09-01 11:25 UTC, f-lab-jake commented on src/features/chat/model/useChatsQuery.tsx
> +  }) as ChatItemType[];
`useQuery`의 `selector`기능을 활용해보세요.

2024-09-01 11:25 UTC, f-lab-jake commented on src/features/chat/model/useFriendsQuery.tsx
> +  const { data, error, isError, isLoading, isSuccess } = useQuery({
`useSuspenseQuery`를 써보세요.

2024-09-01 11:25 UTC, f-lab-jake commented on src/features/chat/ui/ChatRoom.tsx
> +  );
element에 memo를 쓰지마세요. 이유를 생각해오세요.

2024-09-01 11:25 UTC, f-lab-jake commented on src/features/chat/ui/ChatRoom.tsx
> +      setMessages([...initialMessages, ...realTimeMessages]);
상태 설계를 개선해보세요.

2024-09-03 05:29 UTC, xxziiko commented
@f-lab-jake 멘토님, 말씀주신 내용 수정해보았는데, 상태 설계 개선 부분은 감이 잘 안잡히는 것 같습니다

2024-09-23 13:54 UTC, merged