[#1] style 세팅, components UI, Login page UI
f-lab-edu/grape-repo pull request #5
Opened 2024-08-03 17:13 UTC by xxziiko

## 변경사항
- global style (margin, height, font) 전역 설정
- components UI
  - [x] button
  - [x] input
  - [x] header
- layouts
  - [x] form layout
  - [x] page layout
  - [x] button layout
- page
  - [x] login page UI

2024-08-04 05:03 UTC, f-lab-jake requested changes

2024-08-04 05:03 UTC, f-lab-jake commented on src/pages/login/ui/LoginPage.tsx
> +    </>
`whitespace: pre`같은 스타일로 `br` 태그없이 개행할수 있습니다.

2024-08-04 10:11 UTC, xxziiko commented on src/pages/login/ui/LoginPage.tsx
> +    </>
@f-lab-jake 수정했습니다! 혹시 `br` 태그 사용을 지양하는 것일까요.,?!

2024-08-05 10:06 UTC, f-lab-jake commented on src/pages/login/ui/LoginPage.tsx
> +    </>
음 마냥 안좋다기보다는, 보통 문자열 데이터를 따로 빼는경우가 많은데 그때 br로 표현하면서 이스케이핑을 다 해주는게 번거로울거같습니다.

2024-08-05 11:51 UTC, xxziiko commented on src/pages/login/ui/LoginPage.tsx
> +    </>
아하 넵!

2024-08-05 11:51 UTC, merged