[#2] 로그인, 회원가입
f-lab-edu/grape-repo pull request #6
Opened 2024-08-05 12:41 UTC by xxziiko

## 변경사항

- 회원가입 & 로그인 기능
  - [x] 회원가입
  - [x] 이메일 유효성 검사 (이메일 형식 검증)
  - [x] 이메일 중복일 경우 로그인 연결
  - [x] 비밀번호 유효성 검사 (8~16자리)
- 로그인
  - [x] 로그인 후 토큰 발급
  - [x] 인증된 사용자의 정보 저장
- 인증
  - [x] tanstack-router를 사용하여 인증 여부에 따라 접근 제어
  - [x] 인증되지 않은 사용자는 홈페이지로 리다이렉트

2024-08-06 01:14 UTC, f-lab-jake requested changes

2024-08-06 01:14 UTC, f-lab-jake commented on src/features/loginForm/ui/LoginForm.tsx
> +  );
`{ [key: string]: string }` 안좋은 타입입니다.

2024-08-06 01:14 UTC, f-lab-jake commented on src/features/loginForm/model/useLoginMutation.tsx
> +    },
그냥 `mutationFn: signInUser`하면 되겠죠? 오타도있네요.

2024-08-06 05:14 UTC, xxziiko commented on src/features/loginForm/ui/LoginForm.tsx
> +  );
[57edb77](https://github.com/f-lab-edu/grape-repo/pull/6/commits/57edb77b81a530c90420dff232228ff1d749244e) 수정했습니다!

2024-08-06 05:14 UTC, xxziiko commented on src/features/loginForm/model/useLoginMutation.tsx
> +    },
[03affc4](https://github.com/f-lab-edu/grape-repo/pull/6/commits/03affc4386fb120ffde833025979efef1ce08a59) 앗 수정했습니다!

2024-08-06 05:14 UTC, xxziiko commented
@f-lab-jake 말씀주신 내용 수정했습니다!

2024-08-12 01:57 UTC, f-lab-jake approved these changes

2024-08-12 04:16 UTC, merged